"""Cairn — tooling for hybrid human/AI research collaboration."""

from __future__ import annotations

# ``_version.py`` is generated by hatch-vcs at build time. For editable installs
# that pre-date a `pip install -e .` rebuild, fall back to the installed package
# metadata; for a totally uninstalled source checkout, fall back to a sentinel.
try:
    from ._version import __version__
except ImportError:
    try:
        from importlib.metadata import version as _pkg_version

        __version__ = _pkg_version("cairn")
    except Exception:
        __version__ = "0.0.0+unknown"
